# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bubbly < Formula
  desc "Bubbly"
  homepage "https://bubbly.dev/"
  version "0.1.3-alpha"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/valocode/bubbly/releases/download/0.1.3-alpha/bubbly_0.1.3-alpha_darwin_amd64.tar.gz"
      sha256 "a981e5fad74f0b5799a8cbb4fe5a6b0b7dea075a47f7a40da1faca4ece148b83"
    end
    if Hardware::CPU.arm?
      url "https://github.com/valocode/bubbly/releases/download/0.1.3-alpha/bubbly_0.1.3-alpha_darwin_arm64.tar.gz"
      sha256 "9e3ab64ae7f3fd4164bc8805d42d91acc2ccc092f045781f281d366ce1ef0f4c"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/valocode/bubbly/releases/download/0.1.3-alpha/bubbly_0.1.3-alpha_linux_amd64.tar.gz"
      sha256 "3a195764385c20eec25ffc5759adc08d201f14093e10c6cec391680508d0fd7f"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/valocode/bubbly/releases/download/0.1.3-alpha/bubbly_0.1.3-alpha_linux_arm64.tar.gz"
      sha256 "646db4cff494fa93f5ab4963da32a8f136ad5c7a25eeeb4982252673076eedef"
    end
  end

  def install
    bin.install "bubbly"
  end

  test do
    system "#{bin}/bubbly --version"
  end
end
