# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bubbly < Formula
  desc "Bubbly"
  homepage "https://bubbly.dev/"
  version "0.1.7-alpha"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/valocode/bubbly/releases/download/0.1.7-alpha/bubbly_0.1.7-alpha_darwin_amd64.tar.gz"
      sha256 "b4672885ae9f613b670dc2196f9f8b26ad36ab06d95fddc5b3315106aadc9768"
    end
    if Hardware::CPU.arm?
      url "https://github.com/valocode/bubbly/releases/download/0.1.7-alpha/bubbly_0.1.7-alpha_darwin_arm64.tar.gz"
      sha256 "a77a9c2371838c2d96ad4412cce3735b26ea12c2b60734b79f05f1f22e9d205a"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/valocode/bubbly/releases/download/0.1.7-alpha/bubbly_0.1.7-alpha_linux_amd64.tar.gz"
      sha256 "55d17f19543abfe30ec5d6153987c5c00a25bbf6a7d49e858693b3c49f072b16"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/valocode/bubbly/releases/download/0.1.7-alpha/bubbly_0.1.7-alpha_linux_arm64.tar.gz"
      sha256 "f7ddff04f6a5ad4ce21d19e45aecd4ac06d58992ce9a361c86beb386dab78434"
    end
  end

  def install
    bin.install "bubbly"
  end

  test do
    system "#{bin}/bubbly --version"
  end
end
